# Fastlane Configuration for iOS Deployment

default_platform(:ios)

TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"] # Temporary keychain user
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"] # Temporary keychain password
APPLE_KEY_ID = ENV["ASC_KEY_ID"] # App Store Connect API Key ID
APPLE_ISSUER_ID = ENV["ASC_ISSUER_ID"] # App Store Connect Issuer ID
APPLE_KEY_CONTENT = ENV["ASC_KEY"] # App Store Connect API Key Content (Base64 Encoded)


# Function to delete the temporary keychain if it exists
def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

# Function to create a temporary keychain
def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

# Ensure a fresh temporary keychain is created
def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do

  desc "Build and distribute a new Beta build to TestFlight"
  lane :testflight_distribution do

    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    output_name = "example"
    workspace = "example.xcworkspace"
    
    # Ensure a temporary keychain is created
    ensure_temp_keychain(keychain_name, keychain_password)

    # Generate App Store Connect API Key (For Authorization to apple developr account)
    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,
      is_key_content_base64: true,
      duration: 1200,
      in_house: false
    )

    # Increment build number based on the latest TestFlight build number
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )

    # Match provisioning profiles using Git repository
    match(
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key
    )

    # Build the Flutter iOS app
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          ENV["DEVELOPER_APP_IDENTIFIER"] => ENV["PROVISIONING_PROFILE_SPECIFIER"], # Provisioning Profile Name
        }
      }
    )

    # Delete the temporary keychain after build completion
    delete_temp_keychain(keychain_name)

    # Alias for the upload_to_testflight action
    pilot(
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]
    )
  end
end