name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - development # Trigger deployment when pushing to the development branch

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu for the build environment
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: android

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android