name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - development # Trigger deployment when pushing to the development branch

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu for the build environment
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Flutter Version Management CLI
        uses: flutter-actions/setup-fvm@v1

      - name: Install Flutter SDK (Project Version)
        run: |
          # Read the Flutter version from .fvm/fvm_config.json
          FLUTTER_VERSION=$(cat .fvm/fvm_config.json | grep flutterSdkVersion | cut -d '"' -f 4)
          echo "Using Flutter version: $FLUTTER_VERSION"

          # Install the Flutter version specified in the project
          fvm install $FLUTTER_VERSION
          fvm use $FLUTTER_VERSION --force

      - name: Print Flutter SDK version
        run: fvm flutter --version

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: android

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android
