name: IOS Fastlane with TestFlight

on:
  push:
    branches:
      - development

jobs:
  distribute_to_testflight:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.4"
          bundler-cache: true
          working-directory: ios

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Setup Flutter Version Management CLI (FVM)
        uses: flutter-actions/setup-fvm@v1

      - name: Install Flutter SDK (Project Version)
        run: |
          # Read the Flutter version from .fvm/fvm_config.json
          FLUTTER_VERSION=$(cat .fvm/fvm_config.json | grep flutterSdkVersion | cut -d '"' -f 4)
          echo "Using Flutter version: $FLUTTER_VERSION"

          # Install the Flutter version specified in the project
          fvm install $FLUTTER_VERSION
          fvm use $FLUTTER_VERSION --force
      # Ensures that the project uses the correct Flutter SDK version specified in the configuration file

      - name: Print Flutter SDK version
        run: fvm flutter --version

      - name: Install CocoaPods dependencies
        run: |
          fvm flutter precache --ios
          cd ios
          pod install

      - name: Install Fastlane dependencies
        run: |
          cd ios
          bundle install
          
      - name: Debug Environment Variables
        run: |
          echo "FASTLANE_USER: $FASTLANE_USER"
          echo "FASTLANE_PASSWORD: $FASTLANE_PASSWORD"
          echo "FASTLANE_SESSION: $FASTLANE_SESSION"
          echo "ITC_TEAM_ID: $ITC_TEAM_ID"
          echo "TEAM_ID: $TEAM_ID"

      - name: Build and Distribute App to TestFlight
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          
        run: |
          cd ios
          bundle exec fastlane ios testflight_distribution
