name: IOS Fastlane with TestFlight

on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Certificates Repo (Test)
        run: |
          git clone git@github.com:MohamedAhmedHassan894/fastlane.git ~/fastlane

      - name: Install Dependencies
        run: bundle install

      - name: Run Fastlane Match
        run: bundle exec fastlane match appstore
